# Generated by Django 4.1.3 on 2022-11-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=200)),
                ('teacher_email', models.CharField(max_length=200)),
                ('teacher_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
