# Generated by Django 4.1.3 on 2022-11-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='id',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='teachers',
            table='teachers',
        ),
    ]
