# Generated by Django 4.1.3 on 2022-11-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0002_remove_teachers_id_alter_teachers_teacher_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=150)),
                ('Gradebook_number', models.IntegerField()),
                ('Login', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
    ]
